# Generated by Django 3.2 on 2021-04-22 15:02

import banking.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('id', models.CharField(default=banking.models.uuid_str, max_length=100, primary_key=True, serialize=False)),
                ('account_number', models.IntegerField(default=banking.models.get_default_account, editable=False, unique=True)),
                ('balance', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20)),
                ('account_type', models.CharField(choices=[('SV', 'Savings'), ('SL', 'Salary'), ('CT', 'Current'), ('BS', 'Business'), ('OT', 'Other')], max_length=2)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('IA', 'Inactive'), ('HL', 'Hold'), ('BL', 'Blocked'), ('SP', 'Suspended'), ('OT', 'Other')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('id', models.CharField(default=banking.models.uuid_str, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=11, unique=True)),
                ('micr_code', models.CharField(max_length=9, unique=True)),
                ('state', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'unique_together': {('name', 'city')},
            },
        ),
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('id', models.CharField(default=banking.models.uuid_str, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('id', models.CharField(default=banking.models.uuid_str, max_length=100, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(default=banking.models.generate_txn_id, editable=False, max_length=100)),
                ('transaction_type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20)),
                ('transaction_method', models.CharField(choices=[('UPI', 'UPI'), ('NEFT', 'NEFT'), ('IMPS', 'IMPS'), ('RTGS', 'RTGS'), ('ATM', 'ATM'), ('POS', 'POS'), ('WITHDRAW', 'WITHDRAW'), ('OT', 'OTHER'), ('CASH', 'CASH')], max_length=8)),
                ('description', jsonfield.fields.JSONField(default=dict)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_transaction', to='banking.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('id', models.CharField(default=banking.models.uuid_str, max_length=100, primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(editable=False, unique=True)),
                ('date_of_birth', models.DateField()),
                ('pan_card_number', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhar_card_number', models.IntegerField()),
                ('occupation', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=400)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch_customers', to='banking.branch')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CityMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('id', models.CharField(default=banking.models.uuid_str, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='banking.statemaster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('id', models.CharField(default=banking.models.uuid_str, max_length=100, primary_key=True, serialize=False)),
                ('account_number', models.IntegerField()),
                ('ifsc_code', models.CharField(max_length=11)),
                ('contact_number', models.CharField(max_length=16)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiary', to='banking.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('id', models.CharField(default=banking.models.uuid_str, max_length=100, primary_key=True, serialize=False)),
                ('address_line_one', models.CharField(max_length=200)),
                ('address_line_two', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_addresses', to='banking.citymaster')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_address', to='banking.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_account', to='banking.customer'),
        ),
    ]
